INSERT INTO address (version, bnr, city, country, street, zip) VALUES (0, '6', 'Prague', 'Czech Republic', 'Kralicka','100 00');
INSERT INTO address (version, bnr, city, country, street, zip) VALUES (0, '6', 'Prague', 'Czech Republic', 'Kralicka', '100 00');
INSERT INTO address (version, bnr, city, country, street, zip) VALUES (0, '6', 'Prague', 'Czech Republic', 'Kralicka', '100 00');
INSERT INTO address (version, bnr, city, country, street, zip) VALUES (0, '6', 'New York', 'USA', '5th Avenue.', '100 00');


INSERT INTO userentity (version, firstname, lastname, email, password, phone, role, address_id) VALUES (0, 'Zdenek', 'Dusatko', 'dusatze@fel.cvut.cz', MD5('admin'), '607793283', 'customer', 1);
INSERT INTO userentity (version, firstname, lastname, email, password, phone, role, address_id) VALUES (0, 'Zdenek', 'Dusatko', 'admin', MD5('admin'), '607793283', 'manager', 2);
INSERT INTO userentity (version, firstname, lastname, email, password, phone, role, address_id) VALUES (0, 'Zdenek', 'Dusatko', 'employee', MD5('admin'), '607793283', 'storekeeper', 3);
INSERT INTO userentity (version, firstname, lastname, email, password, phone, role, address_id) VALUES (0, 'Clint', 'Eastwood', 'clint@gmail.com', MD5('admin'), '607793283', 'storekeeper', 4);



INSERT INTO category (version, name) VALUES (0, 'Books');
INSERT INTO category (version, name) VALUES (0, 'Music');
INSERT INTO category (version, name) VALUES (0, 'Movies');

INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'The Da Vinci Code by Dan Brown', 8.5, 2, 1, "With The Da Vinci Code, Dan Brown masterfully concocts an intelligent and lucid thriller that marries the gusto of an international murder mystery with a collection of fascinating esoteria culled from 2,000 years of Western history. A murder in the silent after-hour halls of the Louvre museum reveals a sinister plot to uncover a secret that has been protected by a clandestine society since the days of Christ. The victim is a high-ranking agent of this ancient society who, in the moments before his death, manages to leave gruesome clues at the scene that only his granddaughter, noted cryptographer Sophie Neveu, and Robert Langdon, a famed symbologist, can untangle. The duo become both suspects and detectives searching for not only Neveu's grandfather's murderer but also the stunning secret of the ages he was charged to protect. Mere steps ahead of the authorities and the deadly competition, the mystery leads Neveu and Langdon on a breathless flight through France, England, and history itself.");
INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'The Godfather by Mario Puzo', 9.9, 12, 1, "The story of Don Vito Corleone, the head of a New York Mafia family, inspired some of the most successful movies ever. It is in Mario Puzo's The Godfather that Corleone first appears. As Corleone's desperate struggle to control the Mafia underworld unfolds, so does the story of his family. The novel is full of exquisitely detailed characters who, despite leading unconventional lifestyles within a notorious crime family, experience the triumphs and failures of the human condition. Filled with the requisite valor, love, and rancor of a great epic, The Godfather is the definitive gangster novel.");
INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'Sinuhe, the Egyptian by Mika Waltari', 7.5, 4, 1, "First published in the United States in 1949 and widely condemned as obscene, The Egyptian outsold every other novel published that year, and remains a classic; readers worldwide have testified to its life-changing power. It is a full-bodied re-creation of a largely forgotten era in the world’s history: the Egypt of the 14th century B.C.E., when pharaohs and gods contended with the near-collapse of history’s greatest empire. This epic tale encompasses the whole of the then-known world, from Babylon to Crete, from Thebes to Jerusalem, while centering around one unforgettable figure: Sinuhe, a man of mysterious origins who rises from the depths of degradation to become personal physician to Pharaoh Akhnaton.");

INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'Riders on the Storm - The Doors', 11.56, 3, 2, "Here is the book that Rolling Stone called the first Doors biography that feels like it was written for the right reasons, and it is easily the most informed account of the Doors' brief but brilliant life as a group.");
INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'The Wall - Pink Floyd', 20, 5, 2, "Pink Floyd's The Wall is one of the most iconic and imaginative albums in the history of rock music, spawning one of the most ambitious stage show productions ever conceived, and a film that instantly became a cult classic.");
INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'Demon Days - Gorillaz', 9.9, 8, 2, "A side project doesn't usually hit gold, especially when said project is a quirky virtual collective fronted by cartoon characters. But the first, self-titled album by Gorillaz--the brainchild of illustrator Jamie Hewlett and Blur frontman Damon Albarn--actually hit platinum and turned into a surprise worldwide hit. Naturally expectations were a lot higher for Gorillaz's sophomore effort, but Demon Days actually is even better than its predecessor. With producer Dan the Automator Nakamura gone, Albarn, a.k.a. 2D, has paired up with DJ Danger Mouse (responsible for the infamous Grey Album that illegally mixed the Beatles and Jay-Z) to steer the musical ship, while a whole new slew of guests enlivens the proceedings. Albarn has described Demon Days as being darker, but there's a real kooky dance-party vibe coursing through the CD.");


INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'Pulp Fiction - Quentin Tarantino', 13, 1, 3, "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.");
INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'A Clockwork Orange - Stanley Kubrick', 15, 2, 3, "The head of a gang of toughs is conditioned to become physically ill at sex and violence during a prison sentence. When he is released, he's beaten by all of his old adversaries.");
INSERT INTO product (version, name, price, count , category_id, description) VALUES (0, 'Django Unchained - Quentin Tarantino', 10, 0, 3, "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.");
